# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ASUS\programming\qt_programs\wordsearch\words.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_words(object):
    def setupUi(self, words):
        words.setObjectName("words")
        words.resize(752, 674)
        words.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(words)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(words)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel { \n"
"    background-color: rgb(232, 232, 232);\n"
"    font-size:17px;\n"
"    color: rgb(71, 71, 71);\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.frame = QtWidgets.QFrame(words)
        self.frame.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.words_list = QtWidgets.QTableWidget(self.frame_2)
        self.words_list.setStyleSheet("QListWidget {\n"
"    border:1px solid rgb(188, 188, 188); \n"
"}")
        self.words_list.setRowCount(50)
        self.words_list.setColumnCount(1)
        self.words_list.setObjectName("words_list")
        self.words_list.horizontalHeader().setVisible(False)
        self.words_list.horizontalHeader().setStretchLastSection(True)
        self.words_list.verticalHeader().setVisible(False)
        self.words_list.verticalHeader().setCascadingSectionResizes(False)
        self.words_list.verticalHeader().setSortIndicatorShown(False)
        self.words_list.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.words_list)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_btn = QtWidgets.QPushButton(self.frame_3)
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_btn.setStyleSheet("QPushButton {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(212, 212, 212);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(198, 198, 198);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(222, 222, 222);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(188, 188, 188);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"")
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout_2.addWidget(self.add_btn)
        self.remove_btn = QtWidgets.QPushButton(self.frame_3)
        self.remove_btn.setStyleSheet("QPushButton {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(212, 212, 212);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(198, 198, 198);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(222, 222, 222);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(188, 188, 188);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"")
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout_2.addWidget(self.remove_btn)
        self.edi_btn = QtWidgets.QPushButton(self.frame_3)
        self.edi_btn.setStyleSheet("QPushButton {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(212, 212, 212);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(198, 198, 198);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(222, 222, 222);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(188, 188, 188);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"\n"
"")
        self.edi_btn.setObjectName("edi_btn")
        self.verticalLayout_2.addWidget(self.edi_btn)
        self.clear_btn = QtWidgets.QPushButton(self.frame_3)
        self.clear_btn.setStyleSheet("QPushButton {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(212, 212, 212);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(198, 198, 198);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(222, 222, 222);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(188, 188, 188);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"")
        self.clear_btn.setObjectName("clear_btn")
        self.verticalLayout_2.addWidget(self.clear_btn)
        self.import_btn = QtWidgets.QPushButton(self.frame_3)
        self.import_btn.setStyleSheet("QPushButton {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(212, 212, 212);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(198, 198, 198);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(222, 222, 222);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(188, 188, 188);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.import_btn.setObjectName("import_btn")
        self.verticalLayout_2.addWidget(self.import_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(words)
        self.buttonBox.setStyleSheet("QPushButton {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(212, 212, 212);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(198, 198, 198);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(222, 222, 222);\n"
"    font-size:16px;\n"
"    color: rgb(71, 71, 71);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    width:156px;\n"
"    height:32px;\n"
"    background-color: rgb(188, 188, 188);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(188, 188, 188);\n"
"    font-size:16px;\n"
"    color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(words)
        self.buttonBox.accepted.connect(words.accept) # type: ignore
        self.buttonBox.rejected.connect(words.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(words)

    def retranslateUi(self, words):
        _translate = QtCore.QCoreApplication.translate
        words.setWindowTitle(_translate("words", "WordSearch"))
        self.label.setText(_translate("words", "Customize the words for the wordsearch"))
        self.add_btn.setText(_translate("words", "Add"))
        self.remove_btn.setText(_translate("words", "Remove"))
        self.edi_btn.setText(_translate("words", "Edit"))
        self.clear_btn.setText(_translate("words", "Clear"))
        self.import_btn.setText(_translate("words", "Import"))
